### ISSUE TITLE
Add option to show popup start with one character

### ISSUE THREAD

**Issue by phmngocnghia** [dwarvesf/VimMotionApp#12]
![image](https://user-images.githubusercontent.com/36730355/82775033-af222e00-9e70-11ea-94b9-8e2fa5b5da61.png)

The popup is currently displayed 2 characters, and need to press 2 keys to activiate it. I think we should have an option to allow display 1 (Or N character), and require N charcter to activiate feature "click on popup".  For me (and other users?), press 1 chacter will be alot of faster when press 2 chacters.

**Comment by viettrungphan** [comment]
1 character only works for 36 controls at the same time A->Z + 0->9.
Not like a mobile app, the desktop app may have a lot of controls, we can go up to 36*36=1296 instead of 35=6. 
Dock icons + menu bar icons + status bar icons on my Mac already take 40.
