### ISSUE TITLE
Why j scroll up but k scroll down in scroll mode

### ISSUE THREAD

**Issue by tshu-w** [dwarvesf/VimMotionApp#16]
### Describe the bug

After activating scroll mode, j scroll up but k scroll down, It's opposite vim style.

### Steps to reproduce

1. Open any page in Safari
2. `cmd-'`
3. press `j` or `k`
### Environment
macOS 10.15.5

**Comment by tshu-w** [comment]
By the way, there is a similar app [vimac](https://github.com/dexterleng/vimac) which you can refer to.

**Comment by viettrungphan** [comment]
Thanks for your reports. We will add a setting to revert it.

**Comment by viettrungphan** [comment]
Fix in v.1.2.0
