### ISSUE TITLE
Switch active window

### ISSUE THREAD

**Issue by viettrungphan** [dwarvesf/VimMotionApp#17]
### Describe the bug
The feature helps user easy to switch between opened windows.

**Comment by viettrungphan** [comment]
<img width="1680" alt="Screen Shot 2020-05-30 at 08 43 36" src="https://user-images.githubusercontent.com/35858359/83316715-a905c600-a251-11ea-9598-f3dc4f601752.png">
Current Progress 40% for those interested.

**Comment by viettrungphan** [comment]
v1.2.0

**Comment by ranelpadon** [comment]
Thanks for implementing this, really cool feature!
