### ISSUE TITLE
Installation with brew cask install doesnt work

### ISSUE THREAD

**Issue by cwerner1** [dwarvesf/VimMotionApp#25]
Running `brew cask install vimmotion` displays the error message

`
Updating Homebrew...
==> Downloading https://github.com/dwarvesf/VimMotionApp/releases/download/v1.2.
Already downloaded: /Users/christian/Library/Caches/Homebrew/downloads/cf3c0f58dd5775b2510c3330f8723133bdd88878fe042f2a2c22e275ac4186b7--VimMotion.1.2.dmg
==> Verifying SHA-256 checksum for Cask 'vimmotion'.
==> Installing Cask vimmotion
ditto: WARNING: bom /var/folders/2b/ryjl62js723c_x6sjlkvbgl00000gn/T/20200915-3074-da05j4.bom contains no files, nothing copied
==> Purging files for version 1.2.2 of Cask vimmotion
Error: It seems the App source '/usr/local/Caskroom/vimmotion/1.2.2/VimMotion.app' is not there.`

**Comment by viettrungphan** [comment]
We are unable to reproduce the bug. Please clean up - reset your brew and try again.
`brew update-reset`
`brew update`
`brew doctor`
Those brew commands may help.

**Comment by cwerner1** [comment]
After reseting Brew - Installations works

Thanks
