### ISSUE TITLE
WHERE IS THE SOURCE CODE?

### ISSUE THREAD

**Issue by tami5** [dwarvesf/VimMotionApp#30]
Hey, it's a bit odd to see no source code. Where is it hosted, is this a closed source app? why is it even on github? most importantly where is the real license?

I've been wanting to install this utilitiy since it was announced (11 months ago) and now I feel cheated in a away. 

Thanks

**Comment by tieubao** [comment]
@tami5 hey thanks for the issue. We've decided not to open it yet as parts of it are using in another commercial tool. For now we only use Github for Issue tracking.

**Comment by tami5** [comment]
That's very Sad. Good luck. This should be noted in the readme at least.
