### ISSUE TITLE
Can't show Tags for secondary Monitor at FullScreen mode

### ISSUE THREAD

**Issue by viettrungphan** [dwarvesf/VimMotionApp#8]
### Steps to reproduce

1. Attach an external monitor
2. Open window and drag to a secondary monitor
3. Toggle fullscreen mode
4. Press Cmd+; to open VimMotion
5. Nothing showing

**Comment by viettrungphan** [comment]
Fixed (v1.2.0)

**Comment by tieubao** [comment]
👍
